version: "3.3"
services:
  mybookphp3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SKEL_EXTERNAL_PORT:-8090}:80"
    volumes:
      - .:/var/www
    depends_on:
      - mybookdatabase3
    environment:
      - SKEL_DB_HOST=database
      - SKEL_DB_NAME=demo
      - SKEL_DB_USER=demo
      - SKEL_DB_PASS=demo
      - SKEL_DB_PORT=3306
  mybookdatabase3:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=demo
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
  adminer:
      image: adminer
      ports:
        - 8080:8080